name: 'Build and publish from Dockerfile'
inputs:
  docker_image_name:
    description: 'Docker image name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Export DOCKER_TAG
      shell: bash
      run: |
        echo "DOCKER_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Register gcloud as a Docker credential helper
      shell: bash
      run: |
        gcloud --quiet auth configure-docker

    - name: Build Docker image
      shell: bash
      run: |
        docker build . --tag ${{ inputs.docker_image_name }}:${{ env.DOCKER_TAG }}

    - name: Publish the Docker image to Google Container Registry
      shell: bash
      run: |
        docker push ${{ inputs.docker_image_name }}:${{ env.DOCKER_TAG }}
