apiVersion: v1
kind: Service
metadata:
  # Leaving this in for now because other services are
  # relying on this duplicated naming convention
  name: ${SERVICE_NAME}-${SERVICE_NAME}-service
  labels:
    resource: ${SERVICE_NAME}
spec:
  type: ClusterIP
  selector:
    app: ${SERVICE_NAME}
